/// Application bootstrap.
///
/// Initialises Flutter bindings, loads environment config, sets up Firebase,
/// then hands off to [App]. No business logic belongs here.
library;

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_performance/firebase_performance.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';
import 'core/errors/error_boundary.dart';
import 'core/errors/firebase_error_screen.dart';
import 'core/services/analytics_service.dart';
import 'core/services/app_check_service.dart';
import 'core/services/crashlytics_service.dart';
import 'core/services/notification_service.dart';
import 'core/services/remote_config_service.dart';
import 'features/auth/providers/auth_providers.dart';
import 'routing/router.dart';
// Generated by FlutterFire CLI — run 'flutterfire configure' to create this file.
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await dotenv.load(fileName: '.env.development');
  } catch (e) {
    throw StateError(
      'Failed to load .env.development: $e\n'
      'Ensure the file exists and is listed in pubspec.yaml assets.',
    );
  }

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    runApp(
      FirebaseErrorScreen(
        message: 'Firebase failed to initialise: $e\n'
            'Check your Firebase config files '
            '(google-services.json / GoogleService-Info.plist).',
      ),
    );
    return;
  }

  // Disable Performance Monitoring data collection in debug mode so that
  // development traffic does not pollute production metrics. In release
  // builds, automatic traces (app start, network requests) are captured.
  try {
    await FirebasePerformance.instance
        .setPerformanceCollectionEnabled(!kDebugMode);
  } catch (e) {
    if (kDebugMode) {
      debugPrint('[Performance] Failed to configure collection: $e');
    }
  }

  // Create a ProviderContainer early so that App Check and Analytics are
  // resolved through Riverpod rather than instantiated directly.
  final container = ProviderContainer();

  try {
    await container.read(appCheckServiceProvider).activate();
  } catch (e) {
    container.dispose();
    runApp(
      FirebaseErrorScreen(
        message: 'Firebase App Check failed to activate: $e\n'
            'Check your App Check configuration in the Firebase Console.',
      ),
    );
    return;
  }

  // Eagerly initialise analytics so that debug-mode collection is disabled
  // at startup before any events fire.
  container.read(analyticsServiceProvider);

  // Eagerly initialise Crashlytics so that debug-mode collection is disabled
  // at startup and global error handlers are installed before any errors fire.
  final crashlytics = container.read(crashlyticsServiceProvider);

  // Eagerly initialise push notifications — requests permission, retrieves
  // FCM token, and installs foreground/background message handlers.
  try {
    await container.read(notificationServiceProvider).initialise();
  } catch (e) {
    if (kDebugMode) {
      debugPrint('[Notifications] Failed to initialise: $e');
    }
  }

  // Eagerly initialise Remote Config — sets defaults, configures fetch
  // interval, and fetches + activates the latest config from Firebase.
  // If the fetch fails (no internet), cached/default values are used.
  await container.read(remoteConfigServiceProvider).initialise();

  // Route Flutter framework errors (build/layout/paint) to Crashlytics.
  FlutterError.onError = (FlutterErrorDetails details) {
    if (kDebugMode) {
      FlutterError.presentError(details);
    }
    crashlytics.logError(
      details.exception,
      details.stack ?? StackTrace.current,
    );
  };

  // Route unhandled async Dart errors to Crashlytics.
  PlatformDispatcher.instance.onError = (Object error, StackTrace stack) {
    crashlytics.logError(error, stack);
    return true;
  };

  // Create the router with the Riverpod-managed AuthRepository so the router
  // and all providers share the same instance (avoids stale-state bugs).
  final appRouter = createRouter(container.read(authRepositoryProvider));

  runApp(
    ErrorBoundary(
      onRetry: () {}, // App-level retry is a no-op — page-level retries handle recovery
      child: UncontrolledProviderScope(
        container: container,
        child: App(router: appRouter),
      ),
    ),
  );
}
